const dataSource = [
  {
    day: "Monday",
    maquina: 3,
  },
  {
    day: "Tuesday",
    maquina: 2,
  },
  {
    day: "Wednesday",
    maquina: 12,
  },
  {
    day: "Thursday",
    maquina: 4,
  },
  {
    day: "Friday",
    maquina: 6,
  },
  {
    day: "Saturday",
    maquina: 11,
  },
  {
    day: "Sunday",
    maquina: 4,
  },
];

const data = [
  {
    cdFilial: "12",
    dsGrupoPC: "teste",
    dsPontoControle: "teste",
    Data: "20220613",
    Aprovados: "18",
    Reprovados: "2",
    Reprovacao: "50%",
  },
  {
    cdFilial: "11",
    dsGrupoPC: "teste",
    dsPontoControle: "teste",
    Data: "20220613",
    Aprovados: "18",
    Reprovados: "2",
    Reprovacao: "80%",
  },
  {
    cdFilial: "5",
    dsGrupoPC: "teste",
    dsPontoControle: "teste",
    Data: "20220613",
    Aprovados: "1",
    Reprovados: "2",
    Reprovacao: "80%",
  },
  {
    cdFilial: "1",
    dsGrupoPC: "teste",
    dsPontoControle: "teste2",
    Data: "20220613",
    Aprovados: "5",
    Reprovados: "2",
    Reprovacao: "80%",
  },
  {
    cdFilial: "7",
    dsGrupoPC: "teste",
    dsPontoControle: "teste",
    Data: "20220613",
    Aprovados: "2",
    Reprovados: "2",
    Reprovacao: "80%",
  },
  {
    cdFilial: "7",
    dsGrupoPC: "teste",
    dsPontoControle: "teste",
    Data: "20220613",
    Aprovados: "7",
    Reprovados: "2",
    Reprovacao: "80%",
  },
  {
    cdFilial: "7",
    dsGrupoPC: "teste",
    dsPontoControle: "teste2",
    Data: "20220613",
    Aprovados: "9",
    Reprovados: "2",
    Reprovacao: "80%",
  },
  {
    cdFilial: "7",
    dsGrupoPC: "teste",
    dsPontoControle: "teste2",
    Data: "20220613",
    Aprovados: "8",
    Reprovados: "2",
    Reprovacao: "80%",
  },
  {
    cdFilial: "7",
    dsGrupoPC: "teste",
    dsPontoControle: "teste",
    Data: "20220613",
    Aprovados: "22",
    Reprovados: "2",
    Reprovacao: "80%",
  },
  {
    cdFilial: "7",
    dsGrupoPC: "teste",
    dsPontoControle: "teste2",
    Data: "20220613",
    Aprovados: "7",
    Reprovados: "2",
    Reprovacao: "80%",
  },
  {
    cdFilial: "7",
    dsGrupoPC: "teste",
    dsPontoControle: "teste",
    Data: "20220613",
    Aprovados: "15",
    Reprovados: "2",
    Reprovacao: "80%",
  },
  {
    cdFilial: "11",
    dsGrupoPC: "teste",
    dsPontoControle: "teste",
    Data: "20220613",
    Aprovados: "89",
    Reprovados: "2",
    Reprovacao: "80%",
  },
  {
    cdFilial: "11",
    dsGrupoPC: "teste",
    dsPontoControle: "teste",
    Data: "20220613",
    Aprovados: "18",
    Reprovados: "2",
    Reprovacao: "80%",
  },
  {
    cdFilial: "11",
    dsGrupoPC: "teste",
    dsPontoControle: "teste",
    Data: "20220613",
    Aprovados: "18",
    Reprovados: "2",
    Reprovacao: "80%",
  },
];

const dataFon = [
  {
    day: "Monday",
    maquina: 5,
  },
  {
    day: "Tuesday",
    maquina: 0,
  },
  {
    day: "Wednesday",
    maquina: 6,
  },
  {
    day: "Thursday",
    maquina: 1,
  },
  {
    day: "Friday",
    maquina: 6,
  },
  {
    day: "Saturday",
    maquina: 2,
  },
  {
    day: "Sunday",
    maquina: 4,
  },
];
