// const data = [
//   {
//     cdFilial: "12",
//     dsGrupoPC: "teste",
//     dsPontoControle: "teste",
//     Data: "20220613",
//     aprovados: "18",
//     reprovados: "2",
//     reprovacao: "50%",
//   },
//   {
//     cdFilial: "11",
//     dsGrupoPC: "teste",
//     dsPontoControle: "teste",
//     Data: "20220613",
//     aprovados: "18",
//     reprovados: "2",
//     reprovacao: "80%",
//   },
//   {
//     cdFilial: "5",
//     dsGrupoPC: "teste",
//     dsPontoControle: "teste",
//     Data: "20220613",
//     aprovados: "1",
//     reprovados: "2",
//     reprovacao: "80%",
//   },
//   {
//     cdFilial: "1",
//     dsGrupoPC: "teste",
//     dsPontoControle: "teste2",
//     Data: "20220613",
//     aprovados: "5",
//     reprovados: "2",
//     reprovacao: "80%",
//   },
//   {
//     cdFilial: "7",
//     dsGrupoPC: "teste",
//     dsPontoControle: "teste",
//     Data: "20220613",
//     aprovados: "2",
//     reprovados: "2",
//     reprovacao: "80%",
//   },
//   {
//     cdFilial: "7",
//     dsGrupoPC: "teste",
//     dsPontoControle: "teste",
//     Data: "20220613",
//     aprovados: "7",
//     reprovados: "2",
//     reprovacao: "80%",
//   },
//   {
//     cdFilial: "7",
//     dsGrupoPC: "teste",
//     dsPontoControle: "teste2",
//     Data: "20220613",
//     aprovados: "9",
//     reprovados: "2",
//     reprovacao: "80%",
//   },
//   {
//     cdFilial: "7",
//     dsGrupoPC: "teste",
//     dsPontoControle: "teste2",
//     Data: "20220613",
//     aprovados: "8",
//     reprovados: "2",
//     reprovacao: "80%",
//   },
//   {
//     cdFilial: "7",
//     dsGrupoPC: "teste",
//     dsPontoControle: "teste",
//     Data: "20220613",
//     aprovados: "22",
//     reprovados: "2",
//     reprovacao: "80%",
//   },
//   {
//     cdFilial: "7",
//     dsGrupoPC: "teste",
//     dsPontoControle: "teste2",
//     Data: "20220613",
//     aprovados: "7",
//     reprovados: "2",
//     reprovacao: "80%",
//   },
//   {
//     cdFilial: "7",
//     dsGrupoPC: "teste",
//     dsPontoControle: "teste",
//     Data: "20220613",
//     aprovados: "15",
//     reprovados: "2",
//     reprovacao: "80%",
//   },
//   {
//     cdFilial: "11",
//     dsGrupoPC: "teste",
//     dsPontoControle: "teste",
//     Data: "20220613",
//     aprovados: "89",
//     reprovados: "2",
//     reprovacao: "80%",
//   },
//   {
//     cdFilial: "11",
//     dsGrupoPC: "teste",
//     dsPontoControle: "teste",
//     Data: "20220613",
//     aprovados: "18",
//     reprovados: "2",
//     reprovacao: "80%",
//   },
//   {
//     cdFilial: "11",
//     dsGrupoPC: "teste",
//     dsPontoControle: "teste",
//     Data: "20220613",
//     aprovados: "18",
//     reprovados: "2",
//     reprovacao: "80%",
//   },
// ];
